version: '3.7'

services:
  redis-cluster-node-0:
   image: redis:alpine
   command: redis-server /usr/local/etc/redis/redis.conf
   networks:
     - redis_cluster
   ports:
     - "9079:6379"
   volumes:
     - ./redis_conf:/usr/local/etc/redis
     
  redis-cluster-node-1:
   image: redis:alpine
   command: redis-server /usr/local/etc/redis/redis.conf
   networks:
     - redis_cluster
   ports:
     - "9080:6379"
   volumes:
     - ./redis_conf:/usr/local/etc/redis
     
  redis-cluster-node-2:
   image: redis:alpine
   command: redis-server /usr/local/etc/redis/redis.conf
   networks:
     - redis_cluster
   ports:
     - "9081:6379"
   volumes:
     - ./redis_conf:/usr/local/etc/redis

  redis-cluster-node-3:
   image: redis:alpine
   command: redis-server /usr/local/etc/redis/redis.conf
   networks:
     - redis_cluster
   ports:
     - "9082:6379"
   volumes:
     - ./redis_conf:/usr/local/etc/redis

  redis-cluster-node-4:
   image: redis:alpine
   command: redis-server /usr/local/etc/redis/redis.conf
   networks:
     - redis_cluster
   ports:
     - "9083:6379"
   volumes:
     - ./redis_conf:/usr/local/etc/redis

  redis-cluster-node-5:
   image: redis:alpine
   command: redis-server /usr/local/etc/redis/redis.conf
   networks:
     - redis_cluster
   ports:
     - "9084:6379"
   volumes:
     - ./redis_conf:/usr/local/etc/redis


  redis-cluster-configure:
   image: redis:alpine
   command: /usr/local/etc/redis/redis-cluster-create.sh
   networks:
     - redis_cluster
   depends_on:
     - redis-cluster-node-0
     - redis-cluster-node-1
     - redis-cluster-node-2
     - redis-cluster-node-3
     - redis-cluster-node-4
     - redis-cluster-node-5
   volumes:
     - ./redis_conf:/usr/local/etc/redis

networks: 
  redis_cluster:
    driver: bridge
